"use strict";

// Site list for Streamkeys MV3 - Extracted from original Sitelist.js
var STREAMKEYS_SITES = {
  "163": { name: "NetEase Cloud Music", url: "http://music.163.com", controller: "163Controller.js" },
  "7digital": { name: "7digital", url: "http://www.7digital.com", controller: "7digitalController.js" },
  "8tracks": { name: "8tracks", url: "http://www.8tracks.com", controller: "8tracksController.js" },
  "amazon": { name: "Amazon Cloud Player", url: "https://www.amazon.com/gp/dmusic/cloudplayer/player", controller: "AmazonController.js" },
  "ampache": { name: "Ampache", url: "http://ampache.org", controller: "AmpacheController.js" },
  "accuradio": { name: "Accuradio", url: "https://www.accuradio.com", controller: "AccuradioController.js" },
  "airsonic": { name: "AirSonic", url: "https://airsonic.github.io/", controller: "AirsonicController.js" },
  "ambientsleepingpill": { name: "Ambient Sleeping Pill", url: "http://www.ambientsleepingpill.com", controller: "AmbientsleepingpillController.js" },
  "anghami": { name: "Anghami", url: "https://www.anghami.com", controller: "AnghamiController.js" },
  "apple": { name: "Apple Music", url: "https://beta.music.apple.com", controller: "AppleMusicController.js" },
  "arena": { name: "Are.na", url: "https://www.are.na/", controller: "ArenaController.js", alias: ["are"] },
  "asoftmurmur": { name: "A Soft Murmur", url: "http://www.asoftmurmur.com", controller: "AsoftmurmurController.js" },
  "audible": { name: "Audible", url: "http://www.audible.com", controller: "AudibleController.js" },
  "audiotool": { name: "Audiotool", url: "https://www.audiotool.com/", controller: "AudiotoolController.js" },
  "bandcamp": { name: "Bandcamp", url: "http://www.bandcamp.com", controller: "BandcampController.js" },
  "bbc": { name: "BBC Radio", url: "http://www.bbc.co.uk/radio", controller: "BBCRadioController.js" },
  "be-at": { name: "BE-AT.TV", url: "https://be-at.tv", controller: "BeAtTvController.js" },
  "beatport": { name: "Beatport", url: "https://www.beatport.com", controller: "BeatportController.js" },
  "brain": { name: "BrainFM", url: "http://brain.fm", controller: "BrainFMController.js" },
  "castbox": { name: "Castbox", url: "https://castbox.fm", controller: "CastboxController.js" },
  "cloud.caster": { name: "Cloud Caster", url: "http://cloud-caster.com", controller: "CloudCasterController.js", alias: ["cloud-caster"] },
  "coderadio": { name: "Code Radio", url: "https://coderadio.freecodecamp.org/", controller: "CodeRadioController.js" },
  "coursera": { name: "Coursera", url: "http://www.coursera.org", controller: "CourseraController.js" },
  "crave": { name: "Crave", url: "https://www.crave.ca", controller: "CraveController.js" },
  "deezer": { name: "Deezer", url: "http://www.deezer.com", controller: "DeezerController.js" },
  "demodrop": { name: "DemoDrop", url: "http://www.demodrop.com", controller: "DemodropController.js" },
  "di": { name: "Di.fm", url: "http://www.di.fm", controller: "DiController.js" },
  "disco": { name: "Disco.io", url: "http://www.disco.io", controller: "DiscoController.js" },
  "disi": { name: "Disi", url: "http://www.disi.co.il", controller: "DisiController.js" },
  "driveplayer": { name: "Drive Player", url: "http://www.driveplayer.com", controller: "DriveplayerController.js" },
  "duckburgradio": { name: "Duckburg Radio", url: "http://beta.radio-mb.com", controller: "DuckburgRadioController.js", alias: ["radio-mb"] },
  "earbits": { name: "Earbits", url: "http://www.earbits.com", controller: "EarbitsController.js" },
  "egghead": { name: "egghead.io", url: "https://egghead.io", controller: "EggheadController.js" },
  "embedded": { name: "Embedded Element", url: null, controller: "EmbeddedElementController.js" },
  "emby": { name: "Emby", url: "http://app.emby.media", controller: "EmbyController.js" },
  "feedly": { name: "Feedly", url: "http://www.feedly.com", controller: "FeedlyController.js" },
  "focusatwill": { name: "focusatwill", url: "http://www.focusatwill.com", controller: "FocusatwillController.js" },
  "focusmusic": { name: "Focusmusic", url: "https://focusmusic.fm/", controller: "FocusmusicController.js" },
  "friskyradio": { name: "Frisky Radio", url: "https://www.friskyradio.com", controller: "FriskyRadioController.js" },
  "gaana": { name: "Gaana", url: "http://www.gaana.com", controller: "GaanaController.js" },
  "giantbomb": { name: "Giantbomb", url: "http://giantbomb.com", controller: "GiantbombController.js" },
  "play.google": { name: "Google Play Music", url: "http://play.google.com", controller: "GoogleMusicController.js" },
  "podcasts.google": { name: "Google Podcasts", url: "http://podcasts.google.com", controller: "GooglePodcastsController.js" },
  "hearthis": { name: "HearThis.at", url: "http://www.hearthis.at", controller: "HearThisController.js" },
  "hoopla": { name: "Hoopla", url: "https://www.hoopladigital.com", controller: "HooplaController.js", alias: ["hoopladigital"] },
  "hulu": { name: "Hulu", url: "https://www.hulu.com", controller: "HuluController.js" },
  "hypem": { name: "Hypemachine", url: "http://www.hypem.com", controller: "HypemController.js" },
  "hypster": { name: "Hypster", url: "http://www.hypster.com", controller: "HypsterController.js" },
  "ivoox": { name: "iVoox", url: "http://www.ivoox.com", controller: "IvooxController.js" },
  "jamendo": { name: "Jamendo", url: "http://www.jamendo.com", controller: "JamendoController.js" },
  "jango": { name: "Jango", url: "http://www.jango.com", controller: "JangoController.js" },
  "jetsetradio": { name: "Jetset Radio", url: "http://www.jetsetradio.live", controller: "JetsetRadioController.js" },
  "jio": { name: "JioSaavn", url: "https://jiosaavn.com", controller: "JioSaavnController.js" },
  "killtheradio": { name: "Kill The Radio", url: "http://killtheradio.com", controller: "KillTheRadioController.js" },
  "kollekt": { name: "Kollekt", url: "http://kollekt.fm", controller: "KollektController.js" },
  "laracasts": { name: "Laracasts", url: "http://laracasts.com", controller: "LaracastsController.js" },
  "launchpadradio": { name: "Launchpad Radio", url: "http://www.launchpadradio.com", controller: "LaunchpadRadioController.js" },
  "listennotes": { name: "Listen Notes", url: "https://listennotes.com", controller: "ListenNotesController.js" },
  "lofi.cafe": { name: "Lofi Cafe", url: "https://lofi.cafe", controller: "LofiCafeController.js" },
  "lynda": { name: "Lynda", url: "http://www.lynda.com", controller: "LyndaController.js" },
  "mixcloud": { name: "Mixcloud", url: "http://www.mixcloud.com", controller: "MixcloudController.js" },
  "music.amazon": { name: "Amazon Music", url: "https://music.amazon.com", controller: "AmazonMusicController.js" },
  "napster": { name: "Napster", url: "http://www.napster.com", controller: "NapsterController.js", alias: ["rhapsody"] },
  "noisli": { name: "Noisli", url: "http://www.noisli.com", controller: "NoisliController.js" },
  "noonpacific": { name: "Noon Pacific", url: "http://www.noonpacific.com", controller: "NoonPacificController.js" },
  "npr": { name: "NPR One", url: "http://one.npr.org", controller: "NprController.js" },
  "opera": { name: "Opera", url: "http://www.opera.com", controller: "OperaController.js" },
  "overcast": { name: "Overcast", url: "http://overcast.fm", controller: "OvercastController.js" },
  "pandora": { name: "Pandora", url: "http://www.pandora.com", controller: "PandoraController.js" },
  "phish": { name: "Phish.in", url: "http://phish.in", controller: "PhishController.js" },
  "plex": { name: "Plex", url: "http://plex.tv", controller: "PlexController.js" },
  "pluralsight": { name: "Pluralsight", url: "http://www.pluralsight.com", controller: "PluralsightController.js" },
  "pocket": { name: "Pocket Casts", url: "http://playbeta.pocketcasts.com", controller: "PocketCastsController.js" },
  "rainwave": { name: "Rainwave", url: "http://rainwave.cc", controller: "RainwaveController.js" },
  "retro": { name: "Retro", url: "http://radio.retro.sx", controller: "RetroController.js" },
  "saavn": { name: "Saavn", url: "http://www.saavn.com", controller: "SaavnController.js" },
  "shortorange": { name: "ShortOrange", url: "https://shortorange.com", controller: "ShortOrangeController.js" },
  "shortorange-alt": { name: "ShortOrange", url: "https://musictools.us", controller: "ShortOrangeController.js" },
  "slacker": { name: "Slacker", url: "http://www.slacker.com", controller: "SlackerController.js" },
  "soundcloud": { name: "SoundCloud", url: "http://www.soundcloud.com", controller: "SoundcloudController.js" },
  "spotify": { name: "Spotify", url: "https://play.spotify.com", controller: "SpotifyController.js" },
  "stitcher": { name: "Stitcher", url: "http://www.stitcher.com", controller: "StitcherController.js" },
  "streamsquid": { name: "StreamSquid", url: "http://streamsquid.com", controller: "StreamSquidController.js" },
  "subsonic": { name: "Subsonic", url: "http://subsonic.org", controller: "SubsonicController.js" },
  "synology": { name: "Synology", url: "http://synology.com", controller: "SynologyController.js" },
  "teamspeak": { name: "TeamSpeak", url: "http://www.teamspeak.com", controller: "TeamSpeakController.js" },
  "tidal": { name: "Tidal", url: "http://www.tidalhifi.com", controller: "TidalController.js" },
  "tone": { name: "Tone.js", url: "https://tonejs.github.io", controller: "ToneController.js" },
  "tunein": { name: "TuneIn", url: "http://www.tunein.com", controller: "TuneInController.js" },
  "twitch": { name: "Twitch", url: "http://www.twitch.tv", controller: "TwitchController.js" },
  "upbeat": { name: "Upbeat", url: "http://upbeatjs.org", controller: "UpbeatController.js" },
  "vk": { name: "VK", url: "http://vk.com", controller: "VkController.js" },
  "vimeo": { name: "Vimeo", url: "http://www.vimeo.com", controller: "VimeoController.js" },
  "wearegenki": { name: "We Are Genki", url: "http://www.wearegenki.com", controller: "WeAreGenkiController.js" },
  "wingy": { name: "Wingy Music", url: "http://wingymusic.com", controller: "WingyMusicController.js" },
  "xiami": { name: "Xiami", url: "http://www.xiami.com", controller: "XiamiController.js" },
  "yandex": { name: "Yandex", url: "http://music.yandex.ru", controller: "YandexController.js" },
  "youtube": { name: "YouTube", url: "https://youtube.com", controller: "YoutubeController-mv3.js" },
  "youtube-tv": { name: "YouTube TV", url: "https://tv.youtube.com", controller: "YouTubeTvController.js" },
  "zillow": { name: "Zillow", url: "http://www.zillow.com", controller: "ZillowController.js" }
};

// Export for global use (used by background script)
if (typeof window !== "undefined") {
  window.STREAMKEYS_SITES = STREAMKEYS_SITES;
}
