"use strict";

// Site list for Streamkeys MV3 - Extracted from original Sitelist.  "spotify": { name: "Spotify", url: "https://open.spotify.com", controller: "SpotifyController-mv3.js" },s
var STREAMKEYS_SITES = {
  "163": { name: "NetEase Cloud Music", url: "http://music.163.com", controller: "163Controller-mv3.js" },
  "7digital": { name: "7digital", url: "http://www.7digital.com", controller: "7digitalController-mv3.js" },
  "8tracks": { name: "8tracks", url: "http://www.8tracks.com", controller: "8tracksController-mv3.js" },
  "amazon": { name: "Amazon Cloud Player", url: "https://www.amazon.com/gp/dmusic/cloudplayer/player", controller: "AmazonController-mv3.js" },
  "ampache": { name: "Ampache", url: "http://ampache.org", controller: "AmpacheController-mv3.js" },
  "accuradio": { name: "Accuradio", url: "https://www.accuradio.com", controller: "AccuradioController-mv3.js" },
  "airsonic": { name: "AirSonic", url: "https://airsonic.github.io/", controller: "AirsonicController-mv3.js" },
  "ambientsleepingpill": { name: "Ambient Sleeping Pill", url: "http://www.ambientsleepingpill.com", controller: "AmbientsleepingpillController-mv3.js" },
  "anghami": { name: "Anghami", url: "https://www.anghami.com", controller: "AnghamiController-mv3.js" },
  "apple": { name: "Apple Music", url: "https://beta.music.apple.com", controller: "AppleMusicController-mv3.js" },
  "arena": { name: "Are.na", url: "https://www.are.na/", controller: "ArenaController-mv3.js", alias: ["are"] },
  "asoftmurmur": { name: "A Soft Murmur", url: "http://www.asoftmurmur.com", controller: "AsoftmurmurController-mv3.js" },
  "audible": { name: "Audible", url: "http://www.audible.com", controller: "AudibleController-mv3.js" },
  "audiotool": { name: "Audiotool", url: "https://www.audiotool.com/", controller: "AudiotoolController-mv3.js" },
  "bandcamp": { name: "Bandcamp", url: "http://www.bandcamp.com", controller: "BandcampController-mv3.js" },
  "bbc": { name: "BBC Radio", url: "http://www.bbc.co.uk/radio", controller: "BBCRadioController-mv3.js" },
  "be-at": { name: "BE-AT.TV", url: "https://be-at.tv", controller: "BeAtTvController-mv3.js" },
  "beatport": { name: "Beatport", url: "https://www.beatport.com", controller: "BeatportController-mv3.js" },
  "brain": { name: "BrainFM", url: "http://brain.fm", controller: "BrainFMController-mv3.js" },
  "castbox": { name: "Castbox", url: "https://castbox.fm", controller: "CastboxController-mv3.js" },
  "cloud.caster": { name: "Cloud Caster", url: "http://cloud-caster.com", controller: "CloudCasterController-mv3.js", alias: ["cloud-caster"] },
  "coderadio": { name: "Code Radio", url: "https://coderadio.freecodecamp.org/", controller: "CodeRadioController-mv3.js" },
  "coursera": { name: "Coursera", url: "http://www.coursera.org", controller: "CourseraController-mv3.js" },
  "crave": { name: "Crave", url: "https://www.crave.ca", controller: "CraveController-mv3.js" },
  "deezer": { name: "Deezer", url: "http://www.deezer.com", controller: "DeezerController-mv3.js" },
  "demodrop": { name: "DemoDrop", url: "http://www.demodrop.com", controller: "DemodropController-mv3.js" },
  "di": { name: "Di.fm", url: "http://www.di.fm", controller: "DiController-mv3.js" },
  "disco": { name: "Disco.io", url: "http://www.disco.io", controller: "DiscoController-mv3.js" },
  "disi": { name: "Disi", url: "http://www.disi.co.il", controller: "DisiController-mv3.js" },
  "driveplayer": { name: "Drive Player", url: "http://www.driveplayer.com", controller: "DriveplayerController-mv3.js" },
  "duckburgradio": { name: "Duckburg Radio", url: "http://beta.radio-mb.com", controller: "DuckburgRadioController-mv3.js", alias: ["radio-mb"] },
  "earbits": { name: "Earbits", url: "http://www.earbits.com", controller: "EarbitsController-mv3.js" },
  "egghead": { name: "egghead.io", url: "https://egghead.io", controller: "EggheadController-mv3.js" },
  "embedded": { name: "Embedded Element", url: null, controller: "EmbeddedElementController-mv3.js" },
  "emby": { name: "Emby", url: "http://app.emby.media", controller: "EmbyController-mv3.js" },
  "feedly": { name: "Feedly", url: "http://www.feedly.com", controller: "FeedlyController-mv3.js" },
  "focusatwill": { name: "focusatwill", url: "http://www.focusatwill.com", controller: "FocusatwillController-mv3.js" },
  "focusmusic": { name: "Focusmusic", url: "https://focusmusic.fm/", controller: "FocusmusicController-mv3.js" },
  "friskyradio": { name: "Frisky Radio", url: "https://www.friskyradio.com", controller: "FriskyRadioController-mv3.js" },
  "gaana": { name: "Gaana", url: "http://www.gaana.com", controller: "GaanaController-mv3.js" },
  "giantbomb": { name: "Giantbomb", url: "http://giantbomb.com", controller: "GiantbombController-mv3.js" },
  "play.google": { name: "Google Play Music", url: "http://play.google.com", controller: "GoogleMusicController-mv3.js" },
  "podcasts.google": { name: "Google Podcasts", url: "http://podcasts.google.com", controller: "GooglePodcastsController-mv3.js" },
  "hearthis": { name: "HearThis.at", url: "http://www.hearthis.at", controller: "HearThisController-mv3.js" },
  "hoopla": { name: "Hoopla", url: "https://www.hoopladigital.com", controller: "HooplaController-mv3.js", alias: ["hoopladigital"] },
  "hulu": { name: "Hulu", url: "https://www.hulu.com", controller: "HuluController-mv3.js" },
  "hypem": { name: "Hypemachine", url: "http://www.hypem.com", controller: "HypemController-mv3.js" },
  "hypster": { name: "Hypster", url: "http://www.hypster.com", controller: "HypsterController-mv3.js" },
  "ivoox": { name: "iVoox", url: "http://www.ivoox.com", controller: "IvooxController-mv3.js" },
  "jamendo": { name: "Jamendo", url: "http://www.jamendo.com", controller: "JamendoController-mv3.js" },
  "jango": { name: "Jango", url: "http://www.jango.com", controller: "JangoController-mv3.js" },
  "jetsetradio": { name: "Jetset Radio", url: "http://www.jetsetradio.live", controller: "JetsetRadioController-mv3.js" },
  "jio": { name: "JioSaavn", url: "https://jiosaavn.com", controller: "JioSaavnController-mv3.js" },
  "killtheradio": { name: "Kill The Radio", url: "http://killtheradio.com", controller: "KillTheRadioController-mv3.js" },
  "kollekt": { name: "Kollekt", url: "http://kollekt.fm", controller: "KollektController-mv3.js" },
  "laracasts": { name: "Laracasts", url: "http://laracasts.com", controller: "LaracastsController-mv3.js" },
  "launchpadradio": { name: "Launchpad Radio", url: "http://www.launchpadradio.com", controller: "LaunchpadRadioController-mv3.js" },
  "listennotes": { name: "Listen Notes", url: "https://listennotes.com", controller: "ListenNotesController-mv3.js" },
  "lofi.cafe": { name: "Lofi Cafe", url: "https://lofi.cafe", controller: "LofiCafeController-mv3.js" },
  "lynda": { name: "Lynda", url: "http://www.lynda.com", controller: "LyndaController-mv3.js" },
  "mixcloud": { name: "Mixcloud", url: "http://www.mixcloud.com", controller: "MixcloudController-mv3.js" },
  "music.amazon": { name: "Amazon Music", url: "https://music.amazon.com", controller: "AmazonMusicController-mv3.js" },
  "napster": { name: "Napster", url: "http://www.napster.com", controller: "NapsterController-mv3.js", alias: ["rhapsody"] },
  "noisli": { name: "Noisli", url: "http://www.noisli.com", controller: "NoisliController-mv3.js" },
  "noonpacific": { name: "Noon Pacific", url: "http://www.noonpacific.com", controller: "NoonPacificController-mv3.js" },
  "npr": { name: "NPR One", url: "http://one.npr.org", controller: "NprController-mv3.js" },
  "opera": { name: "Opera", url: "http://www.opera.com", controller: "OperaController-mv3.js" },
  "overcast": { name: "Overcast", url: "http://overcast.fm", controller: "OvercastController-mv3.js" },
  "pandora": { name: "Pandora", url: "http://www.pandora.com", controller: "PandoraController-mv3.js" },
  "phish": { name: "Phish.in", url: "http://phish.in", controller: "PhishController-mv3.js" },
  "plex": { name: "Plex", url: "http://plex.tv", controller: "PlexController-mv3.js" },
  "pluralsight": { name: "Pluralsight", url: "http://www.pluralsight.com", controller: "PluralsightController-mv3.js" },
  "pocket": { name: "Pocket Casts", url: "http://playbeta.pocketcasts.com", controller: "PocketCastsController-mv3.js" },
  "rainwave": { name: "Rainwave", url: "http://rainwave.cc", controller: "RainwaveController-mv3.js" },
  "retro": { name: "Retro", url: "http://radio.retro.sx", controller: "RetroController-mv3.js" },
  "saavn": { name: "Saavn", url: "http://www.saavn.com", controller: "SaavnController-mv3.js" },
  "shortorange": { name: "ShortOrange", url: "https://shortorange.com", controller: "ShortOrangeController-mv3.js" },
  "shortorange-alt": { name: "ShortOrange", url: "https://musictools.us", controller: "ShortOrangeController-mv3.js" },
  "slacker": { name: "Slacker", url: "http://www.slacker.com", controller: "SlackerController-mv3.js" },
  "soundcloud": { name: "SoundCloud", url: "http://www.soundcloud.com", controller: "SoundcloudController-mv3.js" },
  "spotify": { name: "Spotify", url: "https://play.spotify.com", controller: "SpotifyController-mv3.js" },
  "stitcher": { name: "Stitcher", url: "http://www.stitcher.com", controller: "StitcherController-mv3.js" },
  "streamsquid": { name: "StreamSquid", url: "http://streamsquid.com", controller: "StreamSquidController-mv3.js" },
  "subsonic": { name: "Subsonic", url: "http://subsonic.org", controller: "SubsonicController-mv3.js" },
  "synology": { name: "Synology", url: "http://synology.com", controller: "SynologyController-mv3.js" },
  "teamspeak": { name: "TeamSpeak", url: "http://www.teamspeak.com", controller: "TeamSpeakController-mv3.js" },
  "tidal": { name: "Tidal", url: "http://www.tidalhifi.com", controller: "TidalController-mv3.js" },
  "tone": { name: "Tone.js", url: "https://tonejs.github.io", controller: "ToneController-mv3.js" },
  "tunein": { name: "TuneIn", url: "http://www.tunein.com", controller: "TuneInController-mv3.js" },
  "twitch": { name: "Twitch", url: "http://www.twitch.tv", controller: "TwitchController-mv3.js" },
  "upbeat": { name: "Upbeat", url: "http://upbeatjs.org", controller: "UpbeatController-mv3.js" },
  "vk": { name: "VK", url: "http://vk.com", controller: "VkController-mv3.js" },
  "vimeo": { name: "Vimeo", url: "http://www.vimeo.com", controller: "VimeoController-mv3.js" },
  "wearegenki": { name: "We Are Genki", url: "http://www.wearegenki.com", controller: "WeAreGenkiController-mv3.js" },
  "wingy": { name: "Wingy Music", url: "http://wingymusic.com", controller: "WingyMusicController-mv3.js" },
  "xiami": { name: "Xiami", url: "http://www.xiami.com", controller: "XiamiController-mv3.js" },
  "yandex": { name: "Yandex", url: "http://music.yandex.ru", controller: "YandexController-mv3.js" },
  "youtube": { name: "YouTube", url: "https://youtube.com", controller: "YoutubeController-mv3.js" },
  "music.youtube": { name: "YouTube Music", url: "https://music.youtube.com", controller: "YoutubeMusicController-mv3.js" },
  "youtube-tv": { name: "YouTube TV", url: "https://tv.youtube.com", controller: "YouTubeTvController-mv3.js" },
  "zillow": { name: "Zillow", url: "http://www.zillow.com", controller: "ZillowController-mv3.js" }
};

// Export for global use (used by background script)
if (typeof window !== "undefined") {
  window.STREAMKEYS_SITES = STREAMKEYS_SITES;
}

// Export for service worker context (MV3)
if (typeof self !== "undefined" && typeof window === "undefined") {
  self.STREAMKEYS_SITES = STREAMKEYS_SITES;
}

// Export for CommonJS/Node (used by Browserify)
if (typeof module !== "undefined" && module.exports) {
  module.exports = STREAMKEYS_SITES;
}
